<?php

namespace App\Repository;

/**
 * InstruccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstruccionRepository extends \Doctrine\ORM\EntityRepository
{
}
