<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR1uejHz\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR1uejHz/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR1uejHz.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR1uejHz\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerR1uejHz\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'R1uejHz',
    'container.build_id' => '75a74eba',
    'container.build_time' => 1595231498,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR1uejHz');
