<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHX2K7Ui\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHX2K7Ui/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHX2K7Ui.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHX2K7Ui\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHX2K7Ui\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HX2K7Ui',
    'container.build_id' => '04aa7e9b',
    'container.build_time' => 1610622738,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHX2K7Ui');
