<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYK332BQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYK332BQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYK332BQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYK332BQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYK332BQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YK332BQ',
    'container.build_id' => 'dbad3d2f',
    'container.build_time' => 1593582504,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYK332BQ');
