<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Instruccion extends \App\Entity\Instruccion implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Instruccion' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Instruccion' . "\0" . 'solicitud', '' . "\0" . 'App\\Entity\\Instruccion' . "\0" . 'trabajador', '' . "\0" . 'App\\Entity\\Instruccion' . "\0" . 'fechaFinalizacion', '' . "\0" . 'App\\Entity\\Instruccion' . "\0" . 'descripcionInstruccion', '' . "\0" . 'App\\Entity\\Instruccion' . "\0" . 'completada'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Instruccion' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Instruccion' . "\0" . 'solicitud', '' . "\0" . 'App\\Entity\\Instruccion' . "\0" . 'trabajador', '' . "\0" . 'App\\Entity\\Instruccion' . "\0" . 'fechaFinalizacion', '' . "\0" . 'App\\Entity\\Instruccion' . "\0" . 'descripcionInstruccion', '' . "\0" . 'App\\Entity\\Instruccion' . "\0" . 'completada'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Instruccion $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionInstruccion($descripcionInstruccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionInstruccion', [$descripcionInstruccion]);

        return parent::setDescripcionInstruccion($descripcionInstruccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionInstruccion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionInstruccion', []);

        return parent::getDescripcionInstruccion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompletada($completada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompletada', [$completada]);

        return parent::setCompletada($completada);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompletada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompletada', []);

        return parent::getCompletada();
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitud()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitud', []);

        return parent::getSolicitud();
    }

    /**
     * {@inheritDoc}
     */
    public function setSolicitud(\App\Entity\Solicitud $solicitud = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSolicitud', [$solicitud]);

        return parent::setSolicitud($solicitud);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrabajador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrabajador', []);

        return parent::getTrabajador();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrabajador(\App\Entity\Trabajador $trabajador = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrabajador', [$trabajador]);

        return parent::setTrabajador($trabajador);
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaFinalizacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaFinalizacion', []);

        return parent::setFechaFinalizacion();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaFinalizacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaFinalizacion', []);

        return parent::getFechaFinalizacion();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
