<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Solicitud extends \App\Entity\Solicitud implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'valorada', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'solicitante', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'destino', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'causaAnulacion', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'causaSuspension', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'fechaSuspension', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'extension', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'trabajadores', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'eventos', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'instrucciones', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'estancia', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'descripcionIncidencia', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'estado', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'tiempoSuspension', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'prioritaria'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'valorada', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'solicitante', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'destino', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'causaAnulacion', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'causaSuspension', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'fechaSuspension', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'fecha', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'extension', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'email', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'trabajadores', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'eventos', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'instrucciones', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'estancia', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'descripcionIncidencia', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'estado', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'tiempoSuspension', '' . "\0" . 'App\\Entity\\Solicitud' . "\0" . 'prioritaria'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Solicitud $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getValorada()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValorada', []);

        return parent::getValorada();
    }

    /**
     * {@inheritDoc}
     */
    public function setValorada($valorada)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValorada', [$valorada]);

        return parent::setValorada($valorada);
    }

    /**
     * {@inheritDoc}
     */
    public function setSolicitante($solicitante)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSolicitante', [$solicitante]);

        return parent::setSolicitante($solicitante);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolicitante()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolicitante', []);

        return parent::getSolicitante();
    }

    /**
     * {@inheritDoc}
     */
    public function addTrabajador(\App\Entity\Trabajador $trabajador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTrabajador', [$trabajador]);

        return parent::addTrabajador($trabajador);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTrabajador(\App\Entity\Trabajador $trabajador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTrabajador', [$trabajador]);

        return parent::removeTrabajador($trabajador);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrabajadores(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrabajadores', []);

        return parent::getTrabajadores();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestino($destino)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestino', [$destino]);

        return parent::setDestino($destino);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestino()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestino', []);

        return parent::getDestino();
    }

    /**
     * {@inheritDoc}
     */
    public function setCausaAnulacion($causaAnulacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCausaAnulacion', [$causaAnulacion]);

        return parent::setCausaAnulacion($causaAnulacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCausaAnulacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCausaAnulacion', []);

        return parent::getCausaAnulacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setCausaSuspension($causaSuspension)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCausaSuspension', [$causaSuspension]);

        return parent::setCausaSuspension($causaSuspension);
    }

    /**
     * {@inheritDoc}
     */
    public function getCausaSuspension()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCausaSuspension', []);

        return parent::getCausaSuspension();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrioritaria($prioritaria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrioritaria', [$prioritaria]);

        return parent::setPrioritaria($prioritaria);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrioritaria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrioritaria', []);

        return parent::getPrioritaria();
    }

    /**
     * {@inheritDoc}
     */
    public function setFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFecha', []);

        return parent::setFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function getFecha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFecha', []);

        return parent::getFecha();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtension($extension)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtension', [$extension]);

        return parent::setExtension($extension);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtension()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtension', []);

        return parent::getExtension();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstancia($estancia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstancia', [$estancia]);

        return parent::setEstancia($estancia);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstancia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstancia', []);

        return parent::getEstancia();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcionIncidencia($descripcionIncidencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcionIncidencia', [$descripcionIncidencia]);

        return parent::setDescripcionIncidencia($descripcionIncidencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcionIncidencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcionIncidencia', []);

        return parent::getDescripcionIncidencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setTiempoSuspension($tiempoSuspension)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTiempoSuspension', [$tiempoSuspension]);

        return parent::setTiempoSuspension($tiempoSuspension);
    }

    /**
     * {@inheritDoc}
     */
    public function getTiempoSuspension()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTiempoSuspension', []);

        return parent::getTiempoSuspension();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaSuspension()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaSuspension', []);

        return parent::setFechaSuspension();
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaSuspension()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaSuspension', []);

        return parent::getFechaSuspension();
    }

    /**
     * {@inheritDoc}
     */
    public function addEvento(\App\Entity\Evento $evento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEvento', [$evento]);

        return parent::addEvento($evento);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEvento(\App\Entity\Evento $evento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEvento', [$evento]);

        return parent::removeEvento($evento);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventos', []);

        return parent::getEventos();
    }

    /**
     * {@inheritDoc}
     */
    public function addInstruccion(\App\Entity\Instruccion $instruccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addInstruccion', [$instruccion]);

        return parent::addInstruccion($instruccion);
    }

    /**
     * {@inheritDoc}
     */
    public function removeInstruccion(\App\Entity\Instruccion $instruccion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeInstruccion', [$instruccion]);

        return parent::removeInstruccion($instruccion);
    }

    /**
     * {@inheritDoc}
     */
    public function getInstrucciones(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInstrucciones', []);

        return parent::getInstrucciones();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
